import express from "express";
import { UserRoutes } from "../modules/basic_modules/user/user.route";
import { managementRoutes } from "../modules/basic_modules/management/management.route";
import { subscriptionRoutes } from "../modules/make_modules/subscription/subscription.route";
import { purchaseRoutes } from "../modules/make_modules/purchasePlan/purchase.route";
import uploadRouter from "../fileUpload/route";
import { statusRoutes } from "../modules/make_modules/status/status.route";
import { TermsRoutes } from "../modules/make_modules/terms/terms.route";
import { PDFSettingRoutes } from "../modules/make_modules/pdf.setting/pdf.setting.route";
import { PDFRoutes } from "../modules/make_modules/pdf.generator/pdf.routes";
import { settingRoutes } from "../modules/make_modules/app.setting/app.setting.route";
import { customerRoutes } from "../modules/make_modules/customer/customer.route";
import { vendorRoutes } from "../modules/make_modules/vendor/vendor.route";
import { productRoutes } from "../modules/make_modules/product/product.route";
import { serviceRoutes } from "../modules/make_modules/service/service.route";
import { invoiceRoutes } from "../modules/make_modules/invoice/invoice.route";
import { invoiceReturnRoutes } from "../modules/make_modules/invoice/invoiceReturn/invoiceReturn.route";
import { salesReceiptRoutes } from "../modules/make_modules/salesReceipt/salesReceipt.route";
import { proformaInvoiceRoutes } from "../modules/make_modules/proformaInvoice/proformaInvoice.route";
import { estimateRoutes } from "../modules/make_modules/estimate/estimate.route";
import { deliveryChallanRoutes } from "../modules/make_modules/deliveryChallan/deliveryChallan.route";
import { creditNoteRoutes } from "../modules/make_modules/creditNote/creditNote.route";
import { paymentReceivedRoutes } from "../modules/make_modules/paymentReceived/paymentReceived.route";
import { purchaseOrderRoutes } from "../modules/make_modules/purchaseOrder/purchaseOrder.route";
import { returnPurchaseRoutes } from "../modules/make_modules/purchaseOrder/returnPurchase/returnPurchase.route";
import { billRoutes } from "../modules/make_modules/bill/bill.route";
import { expensesRoutes } from "../modules/make_modules/expenses/expenses.route";
import { debitNoteRoutes } from "../modules/make_modules/debitNote/debitNote.route";
import { paymentRoutes } from "../modules/make_modules/addPayment/payment.route";
import { EditTitlesRoutes } from "../modules/make_modules/editTitles/editTitles.route";
import { permissionRoutes } from "../modules/make_modules/permission/permission.route";
import { warehouseRoutes } from "../modules/make_modules/warehouse/warehouse.route";
import { proposalRoutes } from "../modules/make_modules/proposal/proposal.route";
import { quotationRoutes } from "../modules/make_modules/quotation/quotation.route";
import { categoryRoutes } from "../modules/make_modules/product/category/category.route";
import { taxRoutes } from "../modules/make_modules/product/tax/tax.route";

const router = express.Router();
router.use("/api/v1/file-upload", uploadRouter);
router.use("/api/v1/user", UserRoutes);
router.use("/api/v1/management", managementRoutes);
router.use("/api/v1/subscription", subscriptionRoutes);
router.use("/api/v1/purchase", purchaseRoutes);
router.use("/api/v1/status", statusRoutes);
router.use("/api/v1/terms", TermsRoutes );
router.use("/api/v1/pdf", PDFSettingRoutes );
router.use("/api/v1/pdf", PDFRoutes );
router.use("/api/v1/setting", settingRoutes );
router.use("/api/v1/customer", customerRoutes );
router.use("/api/v1/vendor", vendorRoutes );
router.use("/api/v1/product", productRoutes );
router.use("/api/v1/service", serviceRoutes );
router.use("/api/v1/category", categoryRoutes );
router.use("/api/v1/tax", taxRoutes );
router.use("/api/v1/invoice", invoiceRoutes);
router.use("/api/v1/invoice-return", invoiceReturnRoutes);
router.use("/api/v1/sales-receipt", salesReceiptRoutes);
router.use("/api/v1/proforma-invoice", proformaInvoiceRoutes);
router.use("/api/v1/estimate", estimateRoutes);
router.use("/api/v1/delivery-challan", deliveryChallanRoutes);
router.use("/api/v1/credit-note", creditNoteRoutes);
router.use("/api/v1/payment-received", paymentReceivedRoutes);
router.use("/api/v1/purchase-order", purchaseOrderRoutes);
router.use("/api/v1/purchase-order-return", returnPurchaseRoutes);
router.use("/api/v1/bill", billRoutes);
router.use("/api/v1/expenses", expensesRoutes);
router.use("/api/v1/debit-note", debitNoteRoutes);
router.use("/api/v1/payment", paymentRoutes);
router.use("/api/v1/edit-titles", EditTitlesRoutes);
router.use("/api/v1/permission", permissionRoutes);
router.use("/api/v1/warehouse", warehouseRoutes);
router.use("/api/v1/proposal", proposalRoutes);
router.use("/api/v1/quotation", quotationRoutes);

export default router;
