import express from "express";
import { UserRoutes } from "../modules/basic_modules/user/user.route";
import { managementRoutes } from "../modules/basic_modules/management/management.route";
import { subscriptionRoutes } from "../modules/make_modules/subscription/subscription.route";
import { subscriptionGateway } from "../modules/make_modules/subscription/guard/subscriptionGateway";
import uploadRouter from "../fileUpload/route";
import { statusRoutes } from "../modules/make_modules/status/status.route";
import { TermsRoutes } from "../modules/make_modules/terms/terms.route";
import { PDFRoutes } from "../modules/make_modules/pdf.generator/pdf.routes";
import { settingHubRoutes } from "../modules/make_modules/setting/setting.route";
import { customerRoutes } from "../modules/make_modules/customer/customer.route";
import { vendorRoutes } from "../modules/make_modules/vendor/vendor.route";
import { productRoutes } from "../modules/make_modules/product/product.route";
import { serviceRoutes } from "../modules/make_modules/service/service.route";
import { invoiceRoutes } from "../modules/make_modules/invoice/invoice.route";
import { invoiceReturnRoutes } from "../modules/make_modules/invoice/invoiceReturn/invoiceReturn.route";
import { salespersonRoutes } from "../modules/make_modules/invoice/salesperson/salesperson.route";
import { salesReceiptRoutes } from "../modules/make_modules/salesReceipt/salesReceipt.route";
import { proformaInvoiceRoutes } from "../modules/make_modules/proformaInvoice/proformaInvoice.route";
import { estimateRoutes } from "../modules/make_modules/estimate/estimate.route";
import { deliveryChallanRoutes } from "../modules/make_modules/deliveryChallan/deliveryChallan.route";
import { paymentReceivedRoutes } from "../modules/make_modules/paymentReceived/paymentReceived.route";
import { purchaseRoutes } from "../modules/make_modules/purchase/purchase.route";
import { billRoutes } from "../modules/make_modules/bill/bill.route";
import { expensesRoutes } from "../modules/make_modules/expenses/expenses.route";
import { paymentRoutes } from "../modules/make_modules/addPayment/payment.route";
import { EditTitlesRoutes } from "../modules/make_modules/editTitles/editTitles.route";
import { permissionRoutes } from "../modules/make_modules/permission/permission.route";
import { proposalRoutes } from "../modules/make_modules/proposal/proposal.route";
import { quotationRoutes } from "../modules/make_modules/quotation/quotation.route";
import { projectRoutes } from "../modules/make_modules/project/project.route";
import { accountRoutes } from "../modules/make_modules/account/account.route";
import { goalRoutes } from "../modules/make_modules/goal/goal.route";
import { budgetPlannerRoutes } from "../modules/make_modules/budgetPlanner/budgetPlanner.route";
import { doubleEntryRoutes } from "../modules/make_modules/doubleEntry/doubleEntry.route";
import { hrmRoutes } from "../modules/make_modules/hrm/hrm.route";
import { categoryRoutes } from "../modules/make_modules/product/category/category.route";
import { taxRoutes } from "../modules/make_modules/product/tax/tax.route";
import { performanceRoutes } from "../modules/make_modules/performance/performance.route";
import { trainingRoutes } from "../modules/make_modules/training/training.route";
import { recruitmentRoutes } from "../modules/make_modules/recruitment/recruitment.route";
import { dashboardRoutes } from "../modules/make_modules/dashboard/dashboard.route";
import { crmRoutes } from "../modules/make_modules/crm/crm.route";
import { formBuilderRoutes } from "../modules/make_modules/formBuilder/formBuilder.route";
import { supportRoutes } from "../modules/make_modules/support/support.route";
import { activitiesRoutes } from "../modules/make_modules/activities/activities.route";

const router = express.Router();

// Feature-gate every /api/v1/:module/* request by the company's active plan (best-effort; superadmin/legacy bypass).
router.use(subscriptionGateway);

router.use("/api/v1/file-upload", uploadRouter);
router.use("/api/v1/user", UserRoutes);
router.use("/api/v1/management", managementRoutes);
router.use("/api/v1/subscription", subscriptionRoutes);
router.use("/api/v1/status", statusRoutes);
router.use("/api/v1/terms", TermsRoutes );
router.use("/api/v1/pdf", PDFRoutes );
router.use("/api/v1/setting", settingHubRoutes );
router.use("/api/v1/customer", customerRoutes );
router.use("/api/v1/vendor", vendorRoutes );
router.use("/api/v1/product", productRoutes );
router.use("/api/v1/service", serviceRoutes );
router.use("/api/v1/category", categoryRoutes );
router.use("/api/v1/tax", taxRoutes );
router.use("/api/v1/invoice", invoiceRoutes);
router.use("/api/v1/invoice-return", invoiceReturnRoutes);
router.use("/api/v1/salesperson", salespersonRoutes);
router.use("/api/v1/sales-receipt", salesReceiptRoutes);
router.use("/api/v1/proforma-invoice", proformaInvoiceRoutes);
router.use("/api/v1/estimate", estimateRoutes);
router.use("/api/v1/delivery-challan", deliveryChallanRoutes);
// Credit/debit notes: use /api/v1/account/credit-notes and /api/v1/account/debit-notes
router.use("/api/v1/payment-received", paymentReceivedRoutes);
router.use("/api/v1/purchase", purchaseRoutes);
router.use("/api/v1/bill", billRoutes);
router.use("/api/v1/expenses", expensesRoutes);
router.use("/api/v1/payment", paymentRoutes);
router.use("/api/v1/edit-titles", EditTitlesRoutes);
router.use("/api/v1/permission", permissionRoutes);
router.use("/api/v1/proposal", proposalRoutes);
router.use("/api/v1/quotation", quotationRoutes);
router.use("/api/v1/project", projectRoutes);
router.use("/api/v1/account", accountRoutes);
router.use("/api/v1/goal", goalRoutes);
router.use("/api/v1/budget-planner", budgetPlannerRoutes);
router.use("/api/v1/double-entry", doubleEntryRoutes);
router.use("/api/v1/hrm", hrmRoutes);
router.use("/api/v1/performance", performanceRoutes);
router.use("/api/v1/training", trainingRoutes);
router.use("/api/v1/recruitment", recruitmentRoutes);
router.use("/api/v1/dashboard", dashboardRoutes);
router.use("/api/v1/crm", crmRoutes);
router.use("/api/v1/form-builder", formBuilderRoutes);
router.use("/api/v1/support", supportRoutes);
router.use("/api/v1/activities", activitiesRoutes);

export default router;
